method: BCENull
#dataset_configs:
dataset_names: [cityscapes, idd, bdd]
eval_dataset_names: [kitti, wilddash, camvid, mapillary]
#eval_dataset_names: []
train_mapping_scheme: _to_cib
val_mapping_scheme: _to_cib_ind
combine_method: concat
num_datasets: 3
num_classes: 28
trainer: null
best_model_keys: [mIoU]
epochs: 50
dataset_key: city_idd_bdd
bce_no_reduce: False
mapillary_special_mapping: False
distribution_threshold: -1