method: BCENull
#dataset_configs:
dataset_names: [cityscapes, bdd, mapillary]
#eval_dataset_names: [kitti, wilddash, camvid, cityscapes, idd, bdd, mapillary]
eval_dataset_names: [kitti, wilddash, camvid, idd]
train_mapping_scheme: _to_bmc
val_mapping_scheme: _to_bmc_ind
combine_method: concat
num_datasets: 3
num_classes: 67
trainer: null
best_model_keys: [mIoU]
epochs: 150
dataset_key: city_bdd_mapillary
bce_no_reduce: True
mapillary_special_mapping: False