defaults:
  - method: bcenull_second_stage
  - logging: dongwan_second_stage
  - model: hrnet_w18_cosine
  - augmentation: base_augmentation
  - distributed: distributed
debug_mode: False
random_seed: 0
use_cudnn: True
lr: 0.001
min_lr: 0
min_lr_epochs: 0
optimizer: AdamW
lr_scheduler: poly
momentum: 0.9
weight_decay: 1e-4
batch_size: 16
num_workers: 32
experiment_name: class_dist_test
resume_training: True
ckpt_path: /home/dongwan/checkpoints_large/bcenull_w18_cosine_sf20_2021-03-07_0/recent149.pth
distribution_path: /home/dongwan/uniseg/label_distributions_sigmoid_null.pkl
log_start: 0
bcenull_v2_loss: True
eval_start_epoch: 0
use_amp: True
dataset_root_paths:
  cityscapes: "/net/acadia14a/data/dokim/mseg_dataset/Cityscapes"
  bdd: "/net/acadia14a/data/dokim/mseg_dataset/BDD/bdd100k/seg"
  idd: "/net/acadia14a/data/dokim/mseg_dataset/IDD/IDD_Segmentation"
  mapillary: "/net/acadia14a/data/dokim/mseg_dataset/Mapillary"
  kitti: "/net/acadia14a/data/dokim/mseg_dataset/Kitti/training"
  wilddash: "/net/acadia14a/data/dokim/mseg_dataset/WildDash"
  camvid: "/net/acadia14a/data/dokim/mseg_dataset/Camvid"